# Generated by Django 3.2.2 on 2022-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_orderitems_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='today_special',
            field=models.BooleanField(default=False),
        ),
    ]
